FROM python:latest

WORKDIR /app

COPY user_management/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY user_management/app.py    ./app.py
COPY user_management/user_management.sql    ./user_management.sql
COPY key.txt     ./key.txt

ENV FLASK_APP=app.py

EXPOSE 5000

CMD ["python", "app.py"]