FROM python:latest

WORKDIR /app

COPY logging/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY logging/app.py    ./app.py
COPY logging/logging.sql    ./logging.sql
COPY key.txt     ./key.txt

ENV FLASK_APP=app.py

EXPOSE 5000

CMD ["python", "app.py"]