FROM python:latest

WORKDIR /app

COPY product_searching/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY product_searching/app.py    ./app.py
COPY product_searching/product_searching.sql    ./product_searching.sql
COPY key.txt     ./key.txt

ENV FLASK_APP=app.py

EXPOSE 5000

CMD ["python", "app.py"]