FROM python:latest

WORKDIR /app

COPY product_management/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY product_management/app.py    ./app.py
COPY product_management/product_management.sql    ./product_management.sql
COPY key.txt     ./key.txt

ENV FLASK_APP=app.py

EXPOSE 5000

CMD ["python", "app.py"]